//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestaurantEntities : DbContext
    {
        public RestaurantEntities()
            : base("name=RestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergen> Allergen { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Menu_Product> Menu_Product { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_Menu> Order_Menu { get; set; }
        public virtual DbSet<Order_Product> Order_Product { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Product_Allergen> Product_Allergen { get; set; }
        public virtual DbSet<User> User { get; set; }
    
        public virtual ObjectResult<GetActiveOrdersByUser_Result> GetActiveOrdersByUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveOrdersByUser_Result>("GetActiveOrdersByUser");
        }
    
        public virtual ObjectResult<string> GetAllergensByMenu(string menuName)
        {
            var menuNameParameter = menuName != null ?
                new ObjectParameter("menuName", menuName) :
                new ObjectParameter("menuName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetAllergensByMenu", menuNameParameter);
        }
    
        public virtual ObjectResult<string> GetAllergensByProduct(string productName)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("productName", productName) :
                new ObjectParameter("productName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetAllergensByProduct", productNameParameter);
        }
    
        public virtual ObjectResult<GetAllMenusWithPriceByCategory_Result> GetAllMenusWithPriceByCategory(string categoryName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllMenusWithPriceByCategory_Result>("GetAllMenusWithPriceByCategory", categoryNameParameter);
        }
    
        public virtual ObjectResult<GetAllOrdersByUser_Result> GetAllOrdersByUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllOrdersByUser_Result>("GetAllOrdersByUser");
        }
    
        public virtual ObjectResult<GetEmployees_Result> GetEmployees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmployees_Result>("GetEmployees");
        }
    
        public virtual ObjectResult<GetProductsByAllergen_Result> GetProductsByAllergen(string allergen)
        {
            var allergenParameter = allergen != null ?
                new ObjectParameter("allergen", allergen) :
                new ObjectParameter("allergen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductsByAllergen_Result>("GetProductsByAllergen", allergenParameter);
        }
    
        public virtual ObjectResult<GetProductsByCategory_Result> GetProductsByCategory(string categoryName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductsByCategory_Result>("GetProductsByCategory", categoryNameParameter);
        }
    
        public virtual ObjectResult<GetProductsByMenu_Result> GetProductsByMenu(string menuName)
        {
            var menuNameParameter = menuName != null ?
                new ObjectParameter("menuName", menuName) :
                new ObjectParameter("menuName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductsByMenu_Result>("GetProductsByMenu", menuNameParameter);
        }
    }
}
